"""Epoch budget: does the comparison hold when both methods train longer?

The main table runs the small graphs at 200 epochs. That budget was inherited,
not chosen, and it turns out to carry the Photo result. Two things fall out of
running both arms at 400.

1. THE COMPARISON IS BUDGET-DEPENDENT, AND NOT IN ONE DIRECTION. Computers
   widens in our favour, CS narrows but holds 5/5, Photo goes from a tie to a
   loss significant on AUC-PR. Reporting only 200 epochs reports the budget that
   flatters us on Photo.

2. MOST OF THE DEMO "REPRODUCTION GAP" ON PHOTO IS THE BUDGET. Our DEMO reaches
   0.8403 at 200 epochs against their published 0.9023, and 0.8879 at 400 - 77%
   of the gap closes with nothing changed but training length. So the claim "we
   cannot reproduce published DEMO" is defensible on Computers (0.058 still
   missing), not on Photo, and on CS we exceed their published number at both
   budgets. A reviewer will run this check; it should be in the paper first.

    python analysis/scripts/build_epoch_table.py
"""

import os
import pandas as pd
from scipy.stats import wilcoxon

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.chdir(ROOT)

PAIRS = [("200", "A_main", "B_demo_mix"), ("400", "E400_outpost", "E400_demo")]
DATASETS = [("photo", "Photo"), ("computers", "Computers"), ("cs", "CS")]


def main():
    d = pd.read_csv("results/results.csv").drop_duplicates(
        subset=["dataset", "method", "seed", "train_seed", "tag"], keep="last")
    pb = pd.read_csv("analysis/tables/published_baselines.csv").set_index("Method")

    rows = []
    for ds, _ in DATASETS:
        for budget, ot, dt in PAIRS:
            a = d[(d.dataset == ds) & (d.method == "outpost") & (d.tag == ot)].set_index("seed")
            b = d[(d.dataset == ds) & (d.method == "demo") & (d.tag == dt)].set_index("seed")
            k = sorted(set(a.index) & set(b.index))
            if len(k) < 3:
                continue
            r = {"dataset": ds, "epochs": int(budget), "n_seeds": len(k)}
            for m, lab in [("best_auroc", "roc"), ("best_aupr", "pr")]:
                dl = a.loc[k, m] - b.loc[k, m]
                r[f"outpost_{lab}"] = round(a.loc[k, m].mean(), 4)
                r[f"demo_{lab}"] = round(b.loc[k, m].mean(), 4)
                r[f"delta_{lab}"] = round(dl.mean(), 4)
                r[f"wins_{lab}"] = int((dl > 0).sum())
                # n=5 floors the two-sided Wilcoxon at 2^-4 = 0.0625, so a
                # unanimous 5/5 cannot reach 0.05 however large the effect.
                r[f"p_{lab}"] = round(wilcoxon(dl).pvalue, 4) if len(k) >= 5 else None
            rows.append(r)
    out = pd.DataFrame(rows)
    out.to_csv("analysis/tables/epoch_budget.csv", index=False)

    gap = []
    for ds, col in DATASETS:
        pub = pb.loc["DEMO", f"{col}_AUC-ROC"]
        a = d[(d.dataset == ds) & (d.method == "demo") & (d.tag == "B_demo_mix")].best_auroc.mean()
        b = d[(d.dataset == ds) & (d.method == "demo") & (d.tag == "E400_demo")].best_auroc.mean()
        gap.append({"dataset": ds, "demo_published": pub,
                    "demo_ours_200": round(a, 4), "demo_ours_400": round(b, 4),
                    "gap_200": round(pub - a, 4), "gap_400": round(pub - b, 4),
                    "frac_gap_closed": round(1 - (pub - b) / (pub - a), 3)})
    gp = pd.DataFrame(gap)
    gp.to_csv("analysis/tables/demo_gap_by_budget.csv", index=False)

    with open("analysis/tables/epoch_budget.md", "w", encoding="utf-8") as f:
        f.write("# Epoch budget\n\nAuto-generated by "
                "`analysis/scripts/build_epoch_table.py`; do not hand-edit.\n\n"
                "## OUTPOST - DEMO (full method, mixup on), paired on seed\n\n")
        f.write(out.to_markdown(index=False))
        f.write("\n\nAt n=5 the two-sided Wilcoxon floors at 2^-4 = 0.0625, so the "
                "unanimous 5/5 results on Computers and CS cannot reach p<0.05 at "
                "this sample size however large the effect. Read the win count.\n\n"
                "## DEMO reproduction gap against training length (AUC-ROC)\n\n")
        f.write(gp.to_markdown(index=False))
        f.write("\n")
    print(out.to_string(index=False))
    print()
    print(gp.to_string(index=False))
    print("\nwrote analysis/tables/epoch_budget.{csv,md}, demo_gap_by_budget.csv")


if __name__ == "__main__":
    main()
