"""Three methods, two selection rules: the ranking table, regenerated from
analysis/appendix.json so it can never go stale while NSReg's CS cells land.

    python analysis/scripts/render_ranking_note.py   # -> analysis/tables/three_method_ranking.md
"""
import json, os
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.chdir(ROOT)
A = json.load(open("analysis/appendix.json"))
ns_n = {r["dataset"]: r["n_nsreg"] for r in A.get("paired_vs_nsreg", [])}

def rank_line(r, k):
    m = r[k]["means"]
    return " › ".join(f"**{x}** {m[x]:.4f}" for x in sorted(m, key=lambda x: -m[x]))

out = ["# Three methods, two selection rules\n",
       "Generated by `analysis/scripts/render_ranking_note.py` from `analysis/appendix.json`; "
       "do not hand-edit. OUTPOST, DEMO (full published method) and NSReg (released code), "
       "all re-run under one protocol at identical seeds and splits, 400 epochs. "
       "*Oracle* = per-metric max over epochs (the published protocol); *val-selected* = "
       "the peak-validation epoch (deployable).\n"]
for title, key in (("All anomalies, AUC-ROC", "three_method_ranking"),
                   ("Unseen classes only, AUC-ROC", "three_method_ranking_unseen")):
    rows = [r for r in A.get(key, []) if len(r["oracle"]["means"]) >= 2]
    out.append(f"\n## {title}\n\n| dataset | n (NSReg) | oracle ranking | val-selected ranking | |\n|---|---|---|---|---|")
    flips = 0
    for r in rows:
        n = ns_n.get(r["dataset"], "")
        prov = " *(provisional)*" if isinstance(n, int) and n < 10 else ""
        flag = "**FLIPS**" if r["ranking_changes"] else "same"
        flips += r["ranking_changes"]
        out.append(f"| {r['dataset']}{prov} | {n} | {rank_line(r,'oracle')} | {rank_line(r,'valsel')} | {flag} |")
    lead = {"oracle": {}, "valsel": {}}
    for r in rows:
        for k in lead:
            lead[k][r[k]["ranking"][0]] = lead[k].get(r[k]["ranking"][0], 0) + 1
    out.append(f"\nRanking changes on **{flips} of {len(rows)}** datasets. Datasets led under oracle: "
               + ", ".join(f"{m} {c}" for m, c in sorted(lead['oracle'].items(), key=lambda kv: -kv[1]))
               + "; under val-selected: "
               + ", ".join(f"{m} {c}" for m, c in sorted(lead['valsel'].items(), key=lambda kv: -kv[1])) + ".")

out.append("\n## NSReg reproduction against its published numbers (AUC-ROC)\n\n| dataset | published | ours @400 (n) | ours @201, their config (n) | Δ @400 |\n|---|---|---|---|---|")
for r in A.get("nsreg_reproduction", []):
    o4 = f"{r['ours_400']:.4f} ({r['n_400']})" if r["ours_400"] else "pending"
    o2 = f"{r['ours_201']:.4f} ({r['n_201']})" if r["ours_201"] else "pending"
    d4 = f"{r['ours_400']-r['published']:+.4f}" if r["ours_400"] else ""
    out.append(f"| {r['dataset']} | {r['published']:.4f} | {o4} | {o2} | {d4} |")
out.append("\nDEMO's re-run lands *below* its published Photo and Computers figures; NSReg's lands "
           "*above* its published figures everywhere. Neither published row is a reliable "
           "ranking of the methods, in opposite directions.")

out.append("\n## OUTPOST minus NSReg, paired on seed\n\n| dataset | n | oracle ROC | oracle PR | val-sel ROC | val-sel PR |\n|---|---|---|---|---|---|")
for r in A.get("paired_vs_nsreg", []):
    f = lambda x: f"{x['delta']:+.4f} ({x['W']}/{x['L']}, p={x['p_wilcoxon']:.3f})"
    prov = " *(provisional)*" if r["n_nsreg"] < 10 else ""
    out.append(f"| {r['dataset']}{prov} | {r['oracle ROC']['n']} | {f(r['oracle ROC'])} | {f(r['oracle PR'])} | {f(r['valsel ROC'])} | {f(r['valsel PR'])} |")
open("analysis/tables/three_method_ranking.md", "w", encoding="utf-8").write("\n".join(out) + "\n")
print("wrote analysis/tables/three_method_ranking.md")
