#!/usr/bin/env python3
"""Multi-seed hyperparameter sensitivity, from the D_* sweep.

METHODOLOGY 8.2 said, in plain text: "With 1-3 runs per point against
+-0.03-0.07 variance, the lambda_un and alpha_plus curves are indicative only. A
publication-grade sensitivity figure requires multi-seed sweeps that have not been
run." campaigns/sensitivity.json is those sweeps - five seeds per point.

The question a sensitivity table has to answer is not "does the number move" but
"does it move more than the seed noise of the default itself". That comparison is
computed here rather than left to the reader.

    python analysis/scripts/sensitivity_table.py -> analysis/tables/sensitivity_multiseed.{json,md}
"""
import glob, json, os, statistics as st
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.chdir(ROOT)

# dataset -> (hyperparameter, default tag, default value, {tag: swept value})
SWEEPS = [
    ("yelp", "hidden_dim", "A_main", "32",
     {"D_hidden16": "16", "D_hidden64": "64"}),
    ("yelp", "alpha_plus", "A_main", "0.05",
     {"D_alpha0.01": "0.01", "D_alpha0.1": "0.10"}),
    ("photo", "lambda_un", "A_main", "1.0",
     {"D_lambda0.5": "0.5", "D_lambda1.25": "1.25", "D_lambda1.5": "1.5"}),
]
METRICS = [("auroc_all", "AUC-ROC"), ("aupr_all", "AUC-PR")]


def arm(ds, tag, key):
    per = defaultdict(list)
    for f in glob.glob(f"results/rotations/{ds}_outpost_s*_{tag}_rot*.json"):
        j = json.load(open(f))
        for r in j["rotations"]:
            per[j["seed"]].append(r["best"][key])
    return {s: st.mean(v) for s, v in per.items()}


def main():
    out, md = [], ["# Multi-seed hyperparameter sensitivity", "",
                   "Generated by `analysis/scripts/sensitivity_table.py`; do not "
                   "hand-edit. Five seeds per swept point against the ten-seed "
                   "default. The column that matters is the last one: a sweep that "
                   "moves the metric by less than the default's own seed spread has "
                   "not shown sensitivity.", ""]
    for ds, hp, dtag, dval, points in SWEEPS:
        for key, mlabel in METRICS:
            base = arm(ds, dtag, key)
            if len(base) < 3:
                continue
            bmean, bsd = st.mean(base.values()), st.stdev(list(base.values()))
            rows, spread = [], []
            for tag, val in points.items():
                a = arm(ds, tag, key)
                if not a:
                    rows.append({"value": val, "tag": tag, "n": 0, "mean": None})
                    continue
                m = st.mean(a.values())
                rows.append({"value": val, "tag": tag, "n": len(a),
                             "mean": round(m, 4),
                             "sd": round(st.stdev(list(a.values())), 4) if len(a) > 1 else None,
                             "delta_vs_default": round(m - bmean, 4)})
                spread.append(m)
            done = [r for r in rows if r["mean"] is not None]
            if not done:
                continue
            allv = spread + [bmean]
            rng = max(allv) - min(allv)
            rec = {"dataset": ds, "hyperparameter": hp, "metric": mlabel,
                   "default_value": dval, "default_mean": round(bmean, 4),
                   "default_seed_sd": round(bsd, 4), "default_n": len(base),
                   "sweep_range": round(rng, 4),
                   "range_over_seed_sd": round(rng / bsd, 2) if bsd else None,
                   "exceeds_seed_noise": bool(bsd and rng > bsd),
                   "points": rows,
                   "complete": all(r["n"] >= 5 for r in done) and len(done) == len(points)}
            out.append(rec)
            md.append(f"## {ds} — `{hp}` ({mlabel})")
            md.append("")
            md.append("| value | n | mean | Δ vs default |")
            md.append("|---|---|---|---|")
            md.append(f"| **{dval}** (default) | {len(base)} | {bmean:.4f} ± {bsd:.4f} | — |")
            for r in sorted(done, key=lambda x: float(x["value"])):
                md.append(f"| {r['value']} | {r['n']} | {r['mean']:.4f}"
                          + (f" ± {r['sd']:.4f}" if r.get("sd") else "")
                          + f" | {r['delta_vs_default']:+.4f} |")
            md.append("")
            verdict = ("**exceeds** the default's seed noise"
                       if rec["exceeds_seed_noise"] else
                       "is **within** the default's seed noise")
            md.append(f"Sweep range {rng:.4f} against a default seed sd of {bsd:.4f}: "
                      f"the sweep {verdict} "
                      f"({rec['range_over_seed_sd']}×)."
                      + ("" if rec["complete"] else
                         "  *Incomplete: not every point has five seeds yet.*"))
            md.append("")
    json.dump(out, open("analysis/tables/sensitivity_multiseed.json", "w"), indent=1)
    open("analysis/tables/sensitivity_multiseed.md", "w").write("\n".join(md) + "\n")
    done = sum(r["complete"] for r in out)
    print(f"{len(out)} sweep×metric records, {done} complete")
    for r in out:
        print(f"  {r['dataset']:6s} {r['hyperparameter']:11s} {r['metric']:8s} "
              f"range {r['sweep_range']:.4f} vs seed sd {r['default_seed_sd']:.4f} "
              f"({r['range_over_seed_sd']}x) "
              f"{'COMPLETE' if r['complete'] else 'partial'}")
    print("\n-> analysis/tables/sensitivity_multiseed.{json,md}")


if __name__ == "__main__":
    main()
