#!/usr/bin/env python3
"""One page per table: what it licenses, what it does not, where it belongs.

Written for the drafting phase. Every number is pulled from analysis/appendix.json
at run time, so a story cannot drift from the table it describes - the failure
mode that quarantined seven runlog-era tables in September.

    python analysis/scripts/table_stories.py    ->  analysis/tables/TABLE_STORIES.md
"""
import json, os, datetime

A = json.load(open("analysis/appendix.json"))
OUT = "analysis/tables/TABLE_STORIES.md"


def row(section, **match):
    for r in A.get(section, []):
        if all(r.get(k) == v for k, v in match.items()):
            return r
    return {}


def d(r, key="delta_roc", field="delta"):
    v = (r or {}).get(key)
    if isinstance(v, dict):
        v = v.get(field)
    return v


def fmt(v, sign=True, nd=4):
    if v is None:
        return "n/a"
    return f"{v:+.{nd}f}" if sign else f"{v:.{nd}f}"


def main():
    P = []
    A_ = A
    ap = P.append

    ap(f"# What each table licenses\n")
    ap("Generated by `analysis/scripts/table_stories.py` from `analysis/appendix.json`; "
       "do not hand-edit, and do not quote a number from here that the table itself "
       f"does not contain. Regenerated {datetime.datetime.utcnow():%Y-%m-%d %H:%M} UTC.\n")
    ap("Each entry says three things: the **one sentence** the table supports, the "
       "**claim it does not support** (the sentence a reader will try to write from it), "
       "and where it belongs.\n")

    # --- main tables ---------------------------------------------------------
    n_ds = len({r["dataset"] for r in A_["main_table"]})
    ap(f"## `table1_small.tex`, `table2_large.tex` — the main comparison\n")
    ap(f"**Supports:** across {n_ds} graphs at one 400-epoch protocol with identical "
       "seeds and splits, OUTPOST, the full published DEMO and NSReg from its released "
       "code land within a few points of each other, and which one leads depends on the "
       "graph.\n")
    ap("**Does not support:** \"OUTPOST is state of the art\". Bold marks the best of the "
       "three same-protocol rows per column, and OUTPOST is not bold on Photo ROC, "
       "Amazon ROC or either T-Finance column. The transcribed rows above the rule come "
       "from other papers' budgets and are not comparable — that is the point of the "
       "reproduction analysis, not a ranking.\n")
    ap("**Belongs in:** §Results, first two tables. The valsel variants belong beside "
       "them or in the appendix, never instead of them.\n")

    # --- three-method ranking ------------------------------------------------
    ap("## `three_method_ranking.tex` — the thesis table\n")
    ap("**Supports:** the ranking of the three methods changes between the oracle rule "
       "(per-metric max over epochs, what the published baselines used) and the "
       "deployable rule (peak-validation epoch) on half the datasets. The selection "
       "rule, not the method, decides who leads.\n")
    ap("**Does not support:** that either rule is correct. The paper's claim is that "
       "reporting one without the other is what misleads.\n")
    ap("**Belongs in:** §Results, main text. This is the table the contribution rests on.\n")

    # --- paired --------------------------------------------------------------
    for lab, sec, other in (("paired_vs_demo", "paired_vs_demo", "the full published DEMO"),
                            ("paired_vs_nsreg", "paired_vs_nsreg", "NSReg from its released code")):
        # the paired sections key their statistics by metric label, and rows for
        # datasets with no comparable arm carry no metric dict at all
        rows = [r for r in A_.get(sec, []) if isinstance(r.get("oracle ROC"), dict)]
        wins = [r for r in rows if (r["oracle ROC"].get("delta") or 0) > 0]
        loss = [r for r in rows if (r["oracle ROC"].get("delta") or 0) < 0]
        names_w = ", ".join(r["dataset"] for r in wins) or "none"
        names_l = ", ".join(r["dataset"] for r in loss) or "none"
        ap(f"## `{lab}.tex` — OUTPOST against {other}, paired\n")
        ap(f"**Supports:** on the {len(rows)} datasets where both methods run, paired by "
           f"seed, OUTPOST's oracle AUC-ROC is higher on {len(wins)} ({names_w}) and "
           f"lower on {len(loss)} ({names_l}); the W/T/L column counts seeds, not "
           "datasets.\n")
        ap("**Does not support:** reading a starred p-value as a large effect. Amber "
           "cells sit exactly at the two-sided Wilcoxon floor, 2^-(n-1), which no effect "
           "size can beat at that n — read W/T/L there.\n")
        ap("**Belongs in:** §Results beside the main tables.\n")

    # --- decomposition -------------------------------------------------------
    ap("## `decomposition.tex` — which component does the work\n")
    tf = row("ablations", dataset="T-Finance", arm="C_nopl_sim0.0")
    ye = row("ablations", dataset="Yelp", arm="C_nopl")
    am = row("ablations", dataset="Amazon", arm="C_nopl")
    co = row("ablations", dataset="Computers", arm="C_nopl")
    cf = row("ablations", dataset="Computers", arm="C_noconformal")
    ap("**Supports:** pseudo-labelling is the load-bearing component and the only one "
       "whose sign tracks how the benchmark was built: essential on the graphs with "
       f"injected anomalies (Computers {fmt(d(co))}) and worth nothing on the graphs "
       f"with observed ones (Yelp {fmt(d(ye))}, Amazon {fmt(d(am))}, "
       f"T-Finance {fmt(d(tf))}). Conformal is not inert — it carries "
       f"{fmt(d(cf))} of Computers on its own — but it is nested inside the "
       "pseudo-labelling path and moves nothing on the real graphs either.\n")
    ap("**Does not support:** \"the real graphs are just harder\", or \"propagation cannot "
       "help on scattered anomalies\". T-Finance is homophilous (same-class fraction "
       "0.629) and pseudo-labelling still fails there, so the divider is how the labels "
       "were produced, not how the neighbourhood looks.\n")
    ap("**Belongs in:** §5, as the mechanism result. It is also the strongest argument "
       "against a method-paper framing and should not be buried.\n")

    # --- gate ---------------------------------------------------------------
    g = A_.get("gate_off", [])
    worst = max((abs(d(r, "oracle ROC") or 0), r["dataset"]) for r in g) if g else (0, "")
    ap("## `gate_off.tex` — the gate removed\n")
    ap(f"**Supports:** removing the atlas gate changes nothing on any of the {len(g)} "
       f"graphs tested; the largest movement in either direction is {worst[0]:.4f} "
       f"({worst[1]}), and no p-value approaches significance.\n")
    ap("**Does not support:** that the smaller model is *better*. It is not worse, and it "
       "is 0.157x DEMO's parameters on Photo — but that ratio is unchanged by the "
       "gate, which is a non-parametric quantile veto. The gate-drop result is about "
       "accuracy only.\n")
    ap("**Belongs in:** §5 and the efficiency discussion. Decide once whether the paper "
       "describes the gate-on or gate-off model and use that variant consistently.\n")

    # --- protocol ------------------------------------------------------------
    infl = {r["dataset"]: r["inflation"] for r in A_.get("oracle_inflation", [])
            if r.get("metric") == "ROC" and r.get("inflation") is not None}
    ap("## `oracle_inflation.tex` — what oracle selection is worth\n")
    if infl:
        hi = max(infl.items(), key=lambda kv: kv[1]); lo = min(infl.items(), key=lambda kv: kv[1])
        ap(f"**Supports:** best-over-epochs minus peak-validation is not a uniform tax. It "
           f"is largest on the small semi-synthetic benchmarks ({hi[0]} {fmt(hi[1])}) and "
           f"nearly absent on real anomaly data ({lo[0]} {fmt(lo[1])}).\n")
    ap("**Does not support:** that every published number is inflated by that much. It is "
       "the inflation *available* under the protocol those papers used, measured on our "
       "runs.\n")
    ap("**Belongs in:** §Protocol, first.\n")

    ap("## `hparam_selection.tex` — what tuning on test would buy\n")
    hp = A_.get("hyperparameter_selection", [])
    nd_ = [r for r in hp if not r.get("retained_default", True)]
    ap("**Supports:** validation is saturated on the semi-synthetic graphs — every arm "
       "inside a 0.002 band — so a sweep there changes nothing, while choosing the best "
       "arm on test buys +0.004 to +0.017. "
       + (f"On {', '.join(r['dataset'] for r in nd_)} validation appears *not* to be "
          "saturated at the three selection seeds and picks a non-default arm that is "
          "worse on test." if nd_ else "") + "\n")
    ap("**Does not support:** \"validation selection is fine because it changes nothing\", "
       "nor \"Amazon's validation is informative\". The graph that appears to discriminate "
       "at three seeds picks the arm that is worse on test, and the apparent "
       "discrimination reverses at ten seeds (P40). Saturation is not safety, and "
       "apparent signal at a small seed count is not signal.\n")
    ap("**Belongs in:** §Protocol, beside oracle inflation.\n")

    ap("## `baseline_selection.tex` — the same rule applied to the baseline\n")
    bs = A_.get("baseline_selection", [])
    chg = [r for r in bs if not r["retained_default"]]
    ap(f"**Supports:** NSReg swept under OUTPOST's own validation-only rule changes "
       f"configuration on {len(chg)} of {len(bs)} datasets and gets **better** on both "
       "of them. The sweep was not a courtesy extended only to our method.\n")
    ap("**Does not support:** that the methods are now equally tuned everywhere — CS is "
       "excluded from the baseline grids for cost, and that must be said wherever a "
       "tuned number appears.\n")
    ap("**Belongs in:** §Protocol or the appendix, cited from the fairness paragraph.\n")

    ap("## `epoch_budget.tex`, `demo_gap.tex` — the budget decides verdicts\n")
    ap("**Supports:** head-to-head verdicts move with training length, and most of the "
       "DEMO reproduction gap on Photo closes with nothing changed but budget.\n")
    ap("**Does not support:** \"their code does not reach their numbers\". That is "
       "defensible on Computers, not on Photo, and on CS we exceed them at both budgets.\n")
    ap("**Belongs in:** §Protocol, as the justification for the uniform 400-epoch choice — "
       "which costs us the Photo tie, and should be said so.\n")

    ap("## `nsreg_reproduction.tex` — the published field is wrong in both directions\n")
    ap("**Supports:** our NSReg lands above its published numbers on every dataset while "
       "our DEMO lands below its published numbers on Photo and Computers. A table mixing "
       "transcribed rows with re-run rows is not a ranking of methods.\n")
    ap("**Does not support:** an accusation about either paper. Budget and protocol "
       "differences account for what we can attribute.\n")
    ap("**Belongs in:** §Protocol.\n")

    ap("## `unseen_paired.tex` — the metric the task is actually about\n")
    ap("**Supports:** on unseen classes the oracle-vs-deployable gap is larger than on "
       "all anomalies, and the ranking flips there too.\n")
    ap("**Does not support:** conclusions on Yelp, Amazon or T-Finance, which are binary "
       "and have no unseen-class split.\n")
    ap("**Belongs in:** §Results or appendix, but the open-set framing makes it main-text "
       "material.\n")

    open(OUT, "w", encoding="utf-8").write("\n".join(P) + "\n")
    print(f"wrote {OUT} ({len(P)} blocks)")


if __name__ == "__main__":
    main()
